apiVersion: apps/v1
kind: Deployment
metadata:
  name: bjss-todo-mvc-depl
  labels:
    app: bjss-todo-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bjss-todo-mvc
  template:
    metadata:
      labels:
        app: bjss-todo-mvc
    spec:
      containers:
        - name: bjss-todo-mvc
          image: public.ecr.aws/g8g7h5m7/bjss-aws:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bjss-todo-mvc-nodeport
spec:
  type: NodePort
  selector:
    app: bjss-todo-mvc
  ports:
    - protocol: TCP
      port: 80
      # para onde sera redirecionado o trafico
      targetPort: 80
      # porta para acesso ao servico
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
    - host: "foo.bar.com"
      http:
        paths:
          - pathType: Prefix
            path: "/bar"
            backend:
              service:
                name: service1
                port:
                  number: 80
    - host: "*.foo.com"
      http:
        paths:
          - pathType: Prefix
            path: "/foo"
            backend:
              service:
                name: service2
                port:
                  number: 80
