apiVersion: apps/v1
kind: Deployment
metadata:
  name: bjss-todo-mvc-depl
  labels:
    app: bjss-todo-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bjss-todo-mvc
  template:
    metadata:
      labels:
        app: bjss-todo-mvc
    spec:
      containers:
        - name: bjss-todo-mvc
          image: public.ecr.aws/g8g7h5m7/bjss-aws:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bjss-todo-mvc-nodeport
spec:
  type: NodePort
  selector:
    app: bjss-todo-mvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
